### ISSUE TITLE
模型部署问题

### ISSUE THREAD

**Issue by zlszhonglongshen** [yeyupiaoling/Pytorch-MobileFaceNet#1]
模型准确率是可以的。大佬有没有考虑过如何进行生产部署的工作，比如进行TensorRT或者ncnn部署的任务？

**Comment by yeyupiaoling** [comment]
没有哦，但改成TensorRT应该不难吧。

**Comment by juren1** [comment]
> 模型准确率是可以的。大佬有没有考虑过如何进行生产部署的工作，比如进行TensorRT或者ncnn部署的任务？

大佬，为啥我直接评估准确率却直有83%这正常吗？不知道你的是多少？可以方便交流一下吗？

**Comment by juren1** [comment]
> 模型准确率是可以的。大佬有没有考虑过如何进行生产部署的工作，比如进行TensorRT或者ncnn部署的任务？

这是我这个评估结果

<img width="1475" height="68" alt="Image" src="https://github.com/user-attachments/assets/8d8b3693-26c8-43a1-8b5a-460505909a56" />
