### ISSUE TITLE
可以分离人脸识别和检测吗，替换mtcnn，只使用MobileFaceNet

### ISSUE THREAD

**Issue by Tecinno4** [yeyupiaoling/Pytorch-MobileFaceNet#10]
hi，大佬，请问下我可以只使用MobileFaceNet吗，不依赖mtcnn，我看这个MobileFaceNet的输入都是先通过mtcnn.infer_image转换成landmark，想问下MobileFaceNet的输入可以单独外接吗？

**Comment by yeyupiaoling** [comment]
可以的，模型都是独立的，只要符合对齐就可以

**Comment by Tecinno4** [comment]
好的谢谢大佬，不过这个训练数据集“emore数据集”链接已经失效了，能更新下吗，或者有没有平替的。

**Comment by Jialy0504** [comment]
可以附带一下所有包的版本吗，下载的时候因为各种版本冲突都快哭了

**Comment by yeyupiaoling** [comment]
https://github.com/yeyupiaoling/Pytorch-MobileFaceNet/blob/master/requirements.txt

**Comment by Jialy0504** [comment]
感谢！

**Comment by Jialy0504** [comment]
您好！我在官网只能下载到libmxnet这个包，运行代码import mxnet as mx时就会报错，请问该如何解决呢

**Comment by yeyupiaoling** [comment]
pip 安装

**Comment by Tecinno4** [comment]
请问有“预测”那部分模型的训练代码吗，这个模型save_model/mobilefacenet.pth的训练方法，我测试人脸相似度，发现斜脸的效果不太好，我想多弄点数据训练或者增加模型的参数。

**Comment by yeyupiaoling** [comment]
这个项目就是训练人脸识别的，
