### ISSUE TITLE
数据集生成

### ISSUE THREAD

**Issue by cencenxy** [yeyupiaoling/Pytorch-MobileFaceNet#11]
hi,大佬，我想知道这个项目用到的face_emore数据集可以自己生产吗？这个数据集太大了，有没有稍微少一些的数据集？非常感谢您。

**Comment by yeyupiaoling** [comment]
数据你小了也不起效果。你可以截取这个数据及其中的一部分，只要不影响标签就可以。

**Comment by cencenxy** [comment]
想具体问一下，这个截取是用mxnet来分割吗？有没有建议怎么截取数据的呢，谢谢

**Comment by yeyupiaoling** [comment]
按照每个人取，一个人的图片全部会在同一个文件夹的，你取一部分人的文件夹就可以了
