### ISSUE TITLE
怎样用自己的数据集进行训练呢？

### ISSUE THREAD

**Issue by 1dAnderson** [yeyupiaoling/Pytorch-MobileFaceNet#2]
给的那个数据集太大了，想自己训练一个小的数据集，大佬知道怎么弄嘛？

**Comment by yeyupiaoling** [comment]
你可以下载这个数据集，然后取里面的一部分训练就可以了。取一部分的文件夹放在dataset/images下

**Comment by 1dAnderson** [comment]
> 你可以下载这个数据集，然后取里面的一部分训练就可以了。取一部分的文件夹放在dataset/images下

我是要完成一个课程大作业，两种机器学习和深度学习两种人脸识别方法对比。大佬给的那个数据集我看了，是.idx和.rec文件格式，再弄到机器学习又很难了。

**Comment by yeyupiaoling** [comment]
这个.idx和.rec文件格式是由前面的jpg转换的，这只是为了加快读取速度。

**Comment by 1dAnderson** [comment]
嗷嗷！明白啦！谢谢大佬！

**Comment by 1dAnderson** [comment]
大佬，为什么这个代码计算train的acc跟test的acc方式不一样呀？而且只计算了train_loss，没有计算test_loss。假如我想看test_loss，有没有简单点的方式改出来呀，第一次做深度学习的项目，很多东西不太会，希望能大佬解答一下，万分感谢！

**Comment by yeyupiaoling** [comment]
这个方式不同，不好改

**Comment by 1dAnderson** [comment]
还有一个问题，我看大佬在介绍里说是用的ArcFace的损失函数，但是代码中train.py里又使用了一个交叉熵损失函数。这两个有什么联系呢？

**Comment by yeyupiaoling** [comment]
https://github.com/yeyupiaoling/Pytorch-MobileFaceNet/blob/master/models/arcmargin.py

**Comment by YU-Anthony** [comment]
同问， 请问 `train.py` 为什么用了 ArcFace 的损失函数还要在之前定义 `criterion = torch.nn.CrossEntropyLoss()` ？

**Comment by 1dAnderson** [comment]
> 

应该是之后定义的吧？
我的理解是，ArcFace只是对数据进行了一些处理，加强了类内紧度和类间间隔。最终分类还是得用交叉熵损失函数
我做报告时画了个图：
![image](https://user-images.githubusercontent.com/64841244/148737299-447d8ba6-43b7-4fb5-aec2-865ceb5732b0.png)
大概就是这样子，个人理解。

**Comment by yeyupiaoling** [comment]
嗯嗯

**Comment by YU-Anthony** [comment]
@1dAnderson @yeyupiaoling 感谢感谢

**Comment by huwei1024** [comment]
自己的训练集数据如何准备呢？需要给到什么样的格式？

**Comment by yeyupiaoling** [comment]
@huwei1024 你可以参考这个修改，前面是图片路径，后面是分类ID

https://github.com/yeyupiaoling/Pytorch-MobileFaceNet/blob/268f820295c078fa32017d7af46cd3073b7c0d61/create_dataset.py#L66

**Comment by huwei1024** [comment]
> @huwei1024 你可以参考这个修改，前面是图片路径，后面是分类ID
> 
> https://github.com/yeyupiaoling/Pytorch-MobileFaceNet/blob/268f820295c078fa32017d7af46cd3073b7c0d61/create_dataset.py#L66

自己的训练数据，如果每个人只有2、3张的照片的话，最后的结果会好吗？

**Comment by yeyupiaoling** [comment]
不会好，你可以跟现在的数据集混在一起训练

**Comment by huwei1024** [comment]
哦，至少需要几张才可以？

**Comment by yeyupiaoling** [comment]
这个也没有明确的数量，数据集里面一般有十几张到几十张

**Comment by juren1** [comment]
想问一下这两个数据集最后执行完create_dataset.py之后会占用多少内存呢？之前尝试结果盘存储不够了，想问一下要用多少内存？好去网上租聘服务器，希望大佬告知？
