### ISSUE TITLE
How to prepare gray image dataset for training

### ISSUE THREAD

**Issue by cubicimage** [yeyupiaoling/Pytorch-MobileFaceNet#4]

**Comment by yeyupiaoling** [comment]
你问题解决了？

**Comment by cubicimage** [comment]
解决了，可以训练跑起来了，后面再确认观察一下结果。


谢谢啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yeyupiaoling/Pytorch-MobileFaceNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月19日(星期一) 晚上7:06
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [yeyupiaoling/Pytorch-MobileFaceNet] How to prepare gray image dataset for training (Issue #4)





 
你问题解决了？

**Comment by cubicimage** [comment]
请问，这个模型转换到onnx的代码有吗？
我尝试自己转onnx，发现mobilefacenet.pth 转换失败。也试过model_params.pth 也转换不了


谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yeyupiaoling/Pytorch-MobileFaceNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月19日(星期一) 晚上7:06
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [yeyupiaoling/Pytorch-MobileFaceNet] How to prepare gray image dataset for training (Issue #4)





 
你问题解决了？

**Comment by yeyupiaoling** [comment]
没有试过转onnx，
