### ISSUE TITLE
加载数据集运行create_dataset文件出现问题

### ISSUE THREAD

**Issue by HIT-yuanqikai** [yeyupiaoling/Pytorch-MobileFaceNet#6]
![image](https://user-images.githubusercontent.com/84231107/194050563-ae36a937-ac3c-4668-bd18-57514b45170a.png)
就是运行这个文件时，它显示转换格式这一步，mx.recordio出现问题，不知博主有什么办法

**Comment by yeyupiaoling** [comment]
这么久应该解决了吧，我先关闭了。
