### ISSUE TITLE
视频检测

### ISSUE THREAD

**Issue by littledevil-fjz** [yeyupiaoling/Pytorch-MobileFaceNet#9]
调用摄像头检测时显示的页面很黑，无法看清人脸，但是可以输出结果

**Comment by yeyupiaoling** [comment]
那什么问题呢？

**Comment by littledevil-fjz** [comment]
>

**Comment by littledevil-fjz** [comment]
> 那什么问题呢？
无法在摄像头检测时画出人脸框体，而且显示的画面整体清晰度较低，请问有什么较好的改善方法吗

**Comment by yeyupiaoling** [comment]
你这个是摄像头的原因吧？

**Comment by littledevil-fjz** [comment]
> 你这个是摄像头的原因吧？

摄像头做别的检测任务在同样环境下是没有问题的，清晰度和亮度相比较都好很多，我再找找原因看看，谢谢

**Comment by yeyupiaoling** [comment]
这个我摄像头是直接打开的，没做任何的处理，所以应该不是我本身程序的问题。

**Comment by littledevil-fjz** [comment]
> 这个我摄像头是直接打开的，没做任何的处理，所以应该不是我本身程序的问题。

好的好的，谢谢大佬
